name: publish
on: 
  push:
    branches:
      - main
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: print working directory
      #   run: |
      #       pwd
      # - name: List files in the repository
      #   run: |
      #       ls -la
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: Build image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile 
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/sonnguyenht/publish-hello-image:latest