name: publish
on: 
  push:
    branches:
      - main
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/sonnguyenht/hello-docker-gcr-demo:latest
          docker run ghcr.io/sonnguyenht/hello-docker-gcr-demo:latest
          docker push ghcr.io/sonnguyenht/hello-docker-gcr-demo:latest
