name: publish
on: 
  push:
    branches:
      - main
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: print working directory
      #   run: |
      #       pwd
      # - name: List files in the repository
      #   run: |
      #       ls -la
      - name: Build the hello-docker Docker image
        run: |
          docker build ${{ github.workspace }}/. --tag ghcr.io/sonnguyenht/hello-docker-gcr-demo:latest
          docker run ghcr.io/sonnguyenht/hello-docker-gcr-demo:latest
          docker push ghcr.io/sonnguyenht/hello-docker-gcr-demo:latest
